version: "2"
services:

    dynamodb:
      image: hilverd/dynamodb
      # volumes:
      #     - ./db:/databases:rw,z
      ports:
        - "8000:8000"
        - "4567:4567"
      mem_limit: 2G

    gremlin-http:
      image: registry.centos.org/datamodel/gremlin:concaf
      volumes:
        - ./scripts:/scripts:z
      entrypoint: /scripts/new-entrypoint.sh
      environment:
        - REST=1
        - DEBUG_GRAPH_METRICS=0
      ports:
        - "8181:8182"
      depends_on:
        - dynamodb
      mem_limit: 2G


    gremlin-websocket:
      image: registry.centos.org/datamodel/gremlin:concaf
      volumes:
        - ./scripts:/scripts:z
        - ./metrics:/opt/dynamodb/dynamodb-titan-storage-backend/server/dynamodb-titan100-storage-backend-1.0.0-hadoop1/metrics
      entrypoint: /scripts/new-entrypoint.sh
      environment:
        - DEBUG_GRAPH_METRICS=1
        - INIT_DELAY=20
      ports:
        - "8182:8182"
      depends_on:
        - dynamodb
      mem_limit: 2G

    # graph:
    #   image: ohamada/graphite-grafana
    #   ports:
    #     - "80:80"
    #     - "8080:8080"
    #     - "2003:2003"
    #     - "2004:2004"
    #     - "7002:7002"
    #   environment:
    #     - PGHOST=postgres
    #     - PGUSER=pgadmin
    #     - PGPASSWORD=pgadmin
    #   volumes:
    #     - ./graphite-grafana/graphite:/var/lib/graphite/whisper
    #   links:
    #     - db:postgres
    #   depends_on:
    #     - db

    # db:
    #   image: postgres:9.5
    #   ports:
    #     - "5432:5432"
    #   expose:
    #     - 5432
    #   environment:
    #     - POSTGRES_USER=pgadmin
    #     - POSTGRES_PASSWORD=pgadmin
    #     - PGDATA=/var/lib/postgresql/data/pgdata
    #   volumes:
    #     - ./graphite-grafana/pgdata:/var/lib/postgresql/data/pgdata:rw
